### ISSUE TITLE
Error: Multiple instances of Gesture Handler were detected

### ISSUE THREAD

**Issue by Albretsen** [HallvardLH/react-native-side-drawer#1]
My projects depends on "react-native-gesture-handler": "~2.9.0", but this package depends on "react-native-gesture-handler": "^2.13.3".

Please lower the dependency version if possible! 2.9.0 might be a good target at least.

When I build with this package installed, I get:

`Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.
> java.lang.Exception: 
  [Gesture Handler] Multiple instances of Gesture Handler were detected. Only one instance of react-native-gesture-handler can be installed in a project. You need to resolve the conflict manually. Check out the documentation: https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting#multiple-instances-of-gesture-handler-were-detected 
  
  Conflict between: 
  - /home/expo/workingdir/build/node_modules/hallvardlh-react-native-drawer/node_modules/react-native-gesture-handler
  - /home/expo/workingdir/build/node_modules/react-native-gesture-handler`

**Comment by HallvardLH** [comment]
Thanks for bringing that to my attention, I should have realized going with the newest version wasn't the best idea. The library now depends on version 2.9.0 of Gesture Handler

**Comment by HallvardLH** [comment]
Thanks for bringing that to my attention, I should have realized going with the newest version wasn't the best idea. The library now depends on version 2.9.0 of Gesture Handler.
